version: 2
jobs:
  validate-json:
    docker:
      - image: hashicorp/packer:1.2.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate
          command: chmod +x ./scripts/validate.sh && ./scripts/validate.sh utility_vm_gcp
  build-image:
    docker:
      - image: hashicorp/packer:1.2.5
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build
          command: chmod +x ./scripts/build.sh && ./scripts/build.sh utility_vm_gcp
          no_output_timeout: 30m
      - store_artifacts:
          path: build-results
          destination: build-results
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          sudo gcloud compute images export --destination-uri gs://vmdk_images/automation-utility-vm.vmdk \
          --image automation-utility-vm --project automation-utility-vm

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-json
      - build-image:
          requires:
            - validate-json
      - deploy:
          requires:
            - build-image
